"""Framework-neutral fault campaigns and localization evaluation."""

from lm_resiliency.failure_types import SystemFailureType
from lm_resiliency.fault_injection.config import (
    SCHEMA_VERSION,
    ClockOrigin,
    ClockSpec,
    ClockType,
    CorruptionOperation,
    FailureType,
    FaultCampaign,
    FaultIncident,
    FaultMagnitude,
    FaultScope,
    FaultSpec,
    FaultSurface,
    FaultTarget,
    IncidentLifetime,
    IncidentTrigger,
    IterationRange,
    RetriggerPolicy,
    SafetyClass,
)
from lm_resiliency.fault_injection.executors import (
    CallbackFaultExecutor,
    FaultExecutionRequest,
    FaultExecutionResult,
    FaultExecutor,
)
from lm_resiliency.fault_injection.injector import (
    FaultInjectionSession,
    UnsupportedFaultError,
    enable_fault_injection,
)
from lm_resiliency.fault_injection.reports import (
    CampaignReport,
    FaultEvaluation,
    FaultInjectionRecord,
    InjectionStatus,
    LocalizationResult,
)
from lm_resiliency.fault_injection.state import (
    CampaignJournal,
    CampaignStateStore,
    JsonCampaignStateStore,
    MemoryCampaignStateStore,
)

__all__ = [
    "SCHEMA_VERSION",
    "CallbackFaultExecutor",
    "CampaignJournal",
    "CampaignReport",
    "CampaignStateStore",
    "ClockOrigin",
    "ClockSpec",
    "ClockType",
    "CorruptionOperation",
    "FailureType",
    "FaultCampaign",
    "FaultEvaluation",
    "FaultExecutionRequest",
    "FaultExecutionResult",
    "FaultExecutor",
    "FaultIncident",
    "FaultInjectionRecord",
    "FaultInjectionSession",
    "FaultMagnitude",
    "FaultScope",
    "FaultSpec",
    "FaultSurface",
    "FaultTarget",
    "IncidentLifetime",
    "IncidentTrigger",
    "InjectionStatus",
    "IterationRange",
    "JsonCampaignStateStore",
    "LocalizationResult",
    "MemoryCampaignStateStore",
    "RetriggerPolicy",
    "SafetyClass",
    "SystemFailureType",
    "UnsupportedFaultError",
    "enable_fault_injection",
]
